/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: ["Poppins", "sans-serif"],
    },
    extend: {
      screens: {
        md: "800px",
      },
    },
    container: {
      center: true,
      padding: "1rem",
      screens: {
        "2xl": "1480px",
      },
    },
    colors: require("tailwindcss-open-color"),
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          base: "#00ffa4",
          1: "#ccffed",
          2: "#aaffe1",
          3: "#80ffd2",
          4: "#55ffc2",
          5: "#2affb3",
          6: "#00d589",
          7: "#00aa6d",
          8: "#008052",
          9: "#005537",
          10: "#003321",
          DEFAULT: "#00ffa4",
          foreground: "#154360",
        },
        accent: {
          base: "#a26bfd",
          1: "#ece1ff",
          2: "#e0cefe",
          3: "#d1b5fe",
          4: "#c19cfe",
          5: "#b284fd",
          6: "#8759d3",
          7: "#6c47a9",
          8: "#51367f",
          9: "#362454",
          10: "#201533",
          DEFAULT: "#a26bfd",
          foreground: "#fff",
        },
        tertiary: {
          base: "#154360",
          1: "#d0d9df",
          2: "#b1c0ca",
          3: "#8aa1b0",
          4: "#638295",
          5: "#3c627b",
          6: "#123850",
          7: "#0e2d40",
          8: "#0b2230",
          9: "#071620",
          10: "#040d13",
        },
        // primary: {
        //   1: "#d0fbfa",
        //   2: "#b0f9f7",
        //   3: "#89f6f4",
        //   4: "#61f3f0",
        //   5: "#39f0ec",
        //   DEFAULT: "#12ede8",
        //   6: "#0fc6c1",
        //   7: "#0c9e9b",
        //   8: "#097774",
        //   9: "#064f4d",
        //   10: "#042f2e",
        //   foreground: "#042f2e",
        // },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        // secondary: {
        //   1: "#cff0e0",
        //   2: "#afe6cb",
        //   3: "#87dab1",
        //   4: "#5ece97",
        //   5: "#36c17d",
        //   DEFAULT: "#0eb563",
        //   6: "#0c9753",
        //   7: "#097942",
        //   8: "#075b32",
        //   9: "#053c21",
        //   10: "#032414",
        //   foreground: "#171625",
        // },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        // accent: {
        //   1: "#d1d0d3",
        //   2: "#b2b1b6",
        //   3: "#8b8b92",
        //   4: "#64646e",
        //   5: "#3e3d49",
        //   DEFAULT: "#171625",
        //   6: "#13121f",
        //   7: "#0f0f19",
        //   8: "#0c0b13",
        //   9: "#08070c",
        //   10: "#050407",
        //   foreground: "#d1d0d3",
        // },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
