import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqQuestions = [
  {
    question: "What is the age range for the stories generated by your AI?",
    answer:
      "Our AI-generated stories are suitable for children aged 3 to 10 years old.",
  },
  {
    question: "How does your AI generate stories?",
    answer:
      "Our AI uses natural language processing (NLP) and machine learning algorithms to analyze the input provided by the user and generate a story that is unique and engaging.",
  },
  {
    question: "Can I customize the characters in the story?",
    answer:
      "Yes, you can customize the characters in the story to include family members, friends, or even pets.",
  },
  {
    question: "What genres of stories are available on your website?",
    answer:
      "We offer a wide range of genres, including adventure, mystery, fantasy, and more.",
  },
];

function Faq() {
  return (
    <div className="px-16 py-16 max-lg:px-4" id="faq">
      <h2 className="mb-12 text-3xl font-bold text-gray-8 max-lg:mb-6 max-lg:text-3xl max-sm:text-2xl max-[450px]:text-lg">
        Frequently asked question
      </h2>

      <Accordion
        type="single"
        collapsible
        className="flex w-full flex-col gap-4"
      >
        {faqQuestions.map((question, i) => (
          <AccordionItem value={`item-${i}`} key={i}>
            <AccordionTrigger className="max-lg:text-lg max-sm:text-left max-sm:text-base">
              {question.question}
            </AccordionTrigger>
            <AccordionContent>{question.answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}

export default Faq;
